name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge.sh
        run: surge --project ./ --domain tu-dominio.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
